services:
  app:
    build:
      context: .
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  mongoexpress:
    image: mongo-express
    ports:
        - "8081:8081"
    depends_on:
      - db
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://evalquiz-material-server-db-1:27017
volumes:
  mongodb:
