services:
  app:
    build:
      context: .
    depends_on:
      - material-server-db
    ports:
      - 50051:50051
  material-server-db:
    image: mongo
  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - material-server-db
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://db:27017
