services:
  app:
    build:
      context: .
    links:
      - db
    ports:
      - 50051:50051
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  mongoexpress:
    image: mongo-express
    ports:
        - "8081:8081"
    links:
      - db
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://db:27017
volumes:
  mongodb:
