services:
  app:
    build:
      context: .
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  mongoexpress:
        image: mongo-express
        ports:
            - "8081:8081"
        environment: 
            - ME_CONFIG_MONGODB_URL=mongodb://evalquiz-material-server-db-1:27017
volumes:
  mongodb:
