services:
  app:
    build:
      context: .
      dockerfile: production-dockerfile
    image: evalquizcontainers.azurecr.io/evalquiz-material-server
    command: python -m evalquiz_material_server.server_component
    ports:
      - 50051:50051
    links:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
