services:
  app:
    build:
      context: .
    volumes:
      - ./:/evalquiz-material-server
    command: python -m evalquiz_material_server.server_component
    ports:
      - 50052:50051
    links:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  mongoexpress:
    image: mongo-express
    ports:
        - "8082:8081"
    links:
      - db
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://db:27017
volumes:
  mongodb:
