services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - mongodb:/data/db
secrets:
   db_root_password:
     file: ./db_root_password.txt
volumes:
  mongodb:
