name: Deploy Sphinx documentation to Pages

on:
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: ./actions/sphinx-notes/action.yml
      with:
        requirements_path: ./requirements.txt
        publish: true
        sphinx_version: 6.2.1
