name: Deploy Sphinx documentation to Pages

on:
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        repository: legendofa/sphinx-notes-recursive
    - id: deployment
      uses: action.yml
      with:
        requirements_path: ./requirements.txt
        publish: true
        sphinx_version: 6.2.1
