# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EvalQuizMaterialServer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://evalquizcontainers.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_94f32dcd15f8459faea1082327732dca }}
          password: ${{ secrets.AzureAppService_ContainerPassword_30f3974b3a3e467da667ca372fa1cc26 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: evalquizcontainers.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_94f32dcd15f8459faea1082327732dca }}/evalquiz-material-server:${{ github.sha }}
          file: ./production-dockerfile
