name: Evalquiz check for code typing, linting and formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install submodules
        run: |
          mkdir -p $HOME/.ssh
          echo '${{ secrets.SUBMODULE_DEPLOY_KEY }}' > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule set-url <path-to-submodule> git@github.com:<organization/submodule>.git
          git submodule update --init --recursive
          git submodule set-url <path-to-submodule> https://github.com/<organization/submodule>.git
          unset GIT_SSH_COMMAND
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Linting with pyflakes
        run: |
          pyflakes .
      - name: Type checking with mypy
        run: |
          mypy --config-file evalquiz_proto/mypy.ini .
      - name: Code format checking with black
        run: |
          black . --check
      # - name: Test with pytest
      # run: |
      #   pytest tests